permalink: /:title/
markdown: kramdown
highlighter: pygments

paginate: 2 #6
comments: true
paginate_path: "/page/:num"

baseurl: "https://njchello.github.io/" # change to empty string ""
domain_name: chello0o.me
google_analytics:

source: source
destination: _site

# cover: /assets/images/header-cover.png

# site title, description, meta_description, meta_keywords
# Details for the RSS feed generator
name: Fernando Moreira
title: Fernando Moreira | Desenvolvimento Web e tudo mais..
description: "Desenvolvedor Front-end/Wordpress, Design Responsivo, HTML5, CSS3 e JavaScript"
meta_description: "Desenvolvedor Front-end/Wordpress, Design Responsivo, HTML5, CSS3 e JavaScript"
meta_keywords: "site, website, loja virtual, lojas virtuais, e-commerce, wordpress, frontend, front-end, html5, css3, javascript, jquery, seo, otimizacao, performance"
url: http://chello0o.me
production_url: http://chello0o.me
repo: https://njchello.github.io/
disqus_shortname: "chello0o"
rss_path: source/
author:
  name: Fernando Moreira
  image: /assets/images/author.jpg
  email: chello0o.me@gggmail.com
  github: https://njchello.github.io/
  bio: "Desenvolvedor Front-end/Wordpress entusiasta de performance, design responsivo e usabilidade, sempre em busca do melhor projeto e de um bom café."

# thought
thought:
  text: I have no special talent. I am only passionately curious.
  author: Albert Einstein

# Plugin: jekyll-assets
assets:
  dirname: /assets
  baseurl: /assets/ # change to /assets/
  sources:
    - assets/images
    - assets/fonts
    - assets/css
    - assets/js
  cache: true
  gzip: [ text/css, application/javascript ]

# Compress HTML
compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  ignore:
    envs: all

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
